import { useState } from 'react';
import { Sparkles, AlertTriangle, CheckCircle2, Zap, Copy, Check, ArrowRight, Layers, Bot, X } from 'lucide-react';
import { mockStorage } from '../services/mockStorage';

const AiAssistantModal = ({ isOpen, onClose, projectId, tasks = [], onTasksUpdated }) => {
  const [activeTab, setActiveTab] = useState('generator'); // 'generator' | 'risk' | 'summary'
  const [promptText, setPromptText] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedCount, setGeneratedCount] = useState(0);
  const [copiedSummary, setCopiedSummary] = useState(false);

  if (!isOpen) return null;

  // 1. Task Generator Submit
  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!promptText.trim()) return;
    setIsGenerating(true);

    setTimeout(() => {
      const newTasks = mockStorage.generateAiTasks(projectId, promptText);
      setIsGenerating(false);
      setGeneratedCount(newTasks.length);
      setPromptText('');
      if (onTasksUpdated) onTasksUpdated();
    }, 900);
  };

  // 2. Risk Detection logic
  const overdueTasks = tasks.filter((t) => t.dueDate && new Date(t.dueDate) < new Date() && t.status !== 'Done');
  const unassignedUrgent = tasks.filter((t) => t.priority === 'urgent' && (!t.assignedTo || t.assignedTo.length === 0));
  const bottleneckColumn = tasks.reduce((acc, t) => {
    if (t.status !== 'Done') {
      acc[t.status] = (acc[t.status] || 0) + 1;
    }
    return acc;
  }, {});

  const highestColumn = Object.entries(bottleneckColumn).sort((a, b) => b[1] - a[1])[0] || ['In Progress', 0];

  const handleFixRisks = () => {
    // 1-click AI resolution: Reassign overdue tasks and balance workload
    overdueTasks.forEach((t) => {
      mockStorage.updateTask(t._id, { priority: 'high', status: 'In Progress' });
    });
    unassignedUrgent.forEach((t) => {
      mockStorage.updateTask(t._id, { assignedTo: [mockStorage.getCurrentUser()] });
    });
    if (onTasksUpdated) onTasksUpdated();
  };

  // 3. AI Executive Summary text
  const totalCount = tasks.length;
  const doneCount = tasks.filter((t) => t.status === 'Done').length;
  const inProgressCount = tasks.filter((t) => t.status === 'In Progress').length;
  const completionRate = totalCount > 0 ? Math.round((doneCount / totalCount) * 100) : 0;

  const executiveSummaryText = `🚀 *FlowBoard AI Sprint Executive Summary*\n\n` +
    `• **Completion Pace**: ${completionRate}% of total backlog (${doneCount}/${totalCount} tasks completed).\n` +
    `• **Active Work**: ${inProgressCount} tasks currently in active development.\n` +
    `• **AI Risk Assessment**: ${overdueTasks.length} overdue tasks detected; ${unassignedUrgent.length} high-priority tasks flag attention.\n\n` +
    `Generated by FlowBoard AI Engine on ${new Date().toLocaleDateString()}`;

  const handleCopySummary = () => {
    navigator.clipboard.writeText(executiveSummaryText);
    setCopiedSummary(true);
    setTimeout(() => setCopiedSummary(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4 animate-in fade-in duration-200">
      <div className="flex max-h-[90vh] w-full max-w-2xl flex-col rounded-3xl border border-slate-200 bg-white dark:border-[#1e2942] dark:bg-[#0c101d] shadow-2xl overflow-hidden">
        
        {/* Modal Header */}
        <div className="flex items-center justify-between border-b border-slate-100 dark:border-[#1e2942]/60 px-6 py-4 bg-gradient-to-r from-brand-650/10 via-indigo-650/5 to-transparent">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-tr from-brand-600 to-indigo-500 shadow-md shadow-brand-500/20">
              <Bot className="h-5 w-5 text-white" />
            </div>
            <div>
              <h2 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
                FlowBoard AI Intelligence
                <span className="rounded-full bg-brand-500/10 px-2 py-0.5 text-[10px] font-extrabold uppercase tracking-wider text-brand-600 dark:text-brand-400 border border-brand-500/20">
                  GPT-4o Powered
                </span>
              </h2>
              <p className="text-xs text-slate-500 dark:text-slate-400">Automated task breakdown, risk auditing, & velocity analytics</p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="rounded-xl p-1.5 text-slate-400 hover:bg-slate-100 dark:hover:bg-[#151c33] dark:hover:text-white transition"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Tab Navigation */}
        <div className="flex border-b border-slate-100 dark:border-[#1e2942]/60 px-6 pt-3 gap-2 bg-slate-50/50 dark:bg-[#080b14]">
          <button
            onClick={() => setActiveTab('generator')}
            className={`flex items-center gap-2 rounded-t-xl px-4 py-2.5 text-xs font-bold transition border-b-2 ${
              activeTab === 'generator'
                ? 'border-brand-500 text-brand-600 dark:text-brand-400 bg-white dark:bg-[#0c101d]'
                : 'border-transparent text-slate-500 hover:text-slate-800 dark:text-slate-400 dark:hover:text-white'
            }`}
          >
            <Sparkles className="h-4 w-4" />
            Task Generator
          </button>
          <button
            onClick={() => setActiveTab('risk')}
            className={`flex items-center gap-2 rounded-t-xl px-4 py-2.5 text-xs font-bold transition border-b-2 ${
              activeTab === 'risk'
                ? 'border-brand-500 text-brand-600 dark:text-brand-400 bg-white dark:bg-[#0c101d]'
                : 'border-transparent text-slate-500 hover:text-slate-800 dark:text-slate-400 dark:hover:text-white'
            }`}
          >
            <AlertTriangle className="h-4 w-4" />
            Risk Audit ({overdueTasks.length + unassignedUrgent.length})
          </button>
          <button
            onClick={() => setActiveTab('summary')}
            className={`flex items-center gap-2 rounded-t-xl px-4 py-2.5 text-xs font-bold transition border-b-2 ${
              activeTab === 'summary'
                ? 'border-brand-500 text-brand-600 dark:text-brand-400 bg-white dark:bg-[#0c101d]'
                : 'border-transparent text-slate-500 hover:text-slate-800 dark:text-slate-400 dark:hover:text-white'
            }`}
          >
            <Zap className="h-4 w-4" />
            Executive Summary
          </button>
        </div>

        {/* Tab Body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">

          {/* 1. TASK GENERATOR */}
          {activeTab === 'generator' && (
            <div className="space-y-5">
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-2">
                  Describe Feature / Epic Scope
                </label>
                <textarea
                  rows={4}
                  value={promptText}
                  onChange={(e) => setPromptText(e.target.value)}
                  placeholder="e.g. Implement OAuth 2.0 authentication with Google login, password hashing, and rate limiting..."
                  className="w-full rounded-2xl border border-slate-200 bg-slate-50 dark:border-[#1e2942] dark:bg-[#080c17] p-4 text-xs text-slate-900 dark:text-slate-100 placeholder-slate-400 outline-none focus:border-brand-500 focus:bg-white dark:focus:bg-[#0c101d] transition"
                />
              </div>

              {/* Preset Prompts Quick Chips */}
              <div>
                <span className="text-[11px] font-semibold text-slate-400 dark:text-slate-500 block mb-2">Try quick presets:</span>
                <div className="flex flex-wrap gap-2">
                  {[
                    'OAuth Auth & MFA Flow',
                    'Dark Mode Token Switcher',
                    'Stripe Checkout & Billing Portal',
                    'REST API Rate Limiting Middleware',
                  ].map((chip) => (
                    <button
                      key={chip}
                      onClick={() => setPromptText(chip)}
                      className="rounded-xl border border-slate-200 dark:border-[#1e2942] bg-white dark:bg-[#12182b] px-3 py-1.5 text-xs text-slate-700 dark:text-slate-300 hover:border-brand-500 hover:text-brand-500 transition"
                    >
                      + {chip}
                    </button>
                  ))}
                </div>
              </div>

              {generatedCount > 0 && (
                <div className="flex items-center gap-2 rounded-2xl bg-emerald-500/10 border border-emerald-550/20 p-4 text-xs font-bold text-emerald-600 dark:text-emerald-400">
                  <CheckCircle2 className="h-4 w-4 shrink-0" />
                  <span>Success! Added {generatedCount} AI-structured tasks directly to your project Kanban board.</span>
                </div>
              )}

              <div className="flex justify-end pt-2">
                <button
                  onClick={handleGenerate}
                  disabled={isGenerating || !promptText.trim()}
                  className="flex items-center gap-2 rounded-2xl bg-gradient-to-r from-brand-600 to-indigo-600 px-6 py-3 text-xs font-bold text-white hover:brightness-110 disabled:opacity-50 transition shadow-lg shadow-brand-500/25"
                >
                  {isGenerating ? (
                    <>
                      <div className="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent" />
                      <span>Synthesizing Tasks...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-4 w-4" />
                      <span>Generate Tasks with AI</span>
                    </>
                  )}
                </button>
              </div>
            </div>
          )}

          {/* 2. RISK AUDIT */}
          {activeTab === 'risk' && (
            <div className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="rounded-2xl border border-red-500/20 bg-red-500/5 p-4">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-bold text-red-500">Overdue Tasks</span>
                    <AlertTriangle className="h-4 w-4 text-red-500" />
                  </div>
                  <span className="text-2xl font-black text-slate-900 dark:text-white">{overdueTasks.length}</span>
                  <p className="text-[10px] text-slate-500 mt-1">Passed due date</p>
                </div>

                <div className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-4">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-bold text-amber-500">Unassigned Urgent</span>
                    <Zap className="h-4 w-4 text-amber-500" />
                  </div>
                  <span className="text-2xl font-black text-slate-900 dark:text-white">{unassignedUrgent.length}</span>
                  <p className="text-[10px] text-slate-500 mt-1">Requires team owner</p>
                </div>

                <div className="rounded-2xl border border-indigo-500/20 bg-indigo-500/5 p-4">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-bold text-indigo-500">Column Bottleneck</span>
                    <Layers className="h-4 w-4 text-indigo-500" />
                  </div>
                  <span className="text-base font-bold text-slate-900 dark:text-white truncate block">{highestColumn[0]}</span>
                  <p className="text-[10px] text-slate-500 mt-1">{highestColumn[1]} active tasks stacked</p>
                </div>
              </div>

              {/* Risk Details List */}
              <div className="space-y-3">
                <h4 className="text-xs font-bold text-slate-800 dark:text-slate-200 uppercase tracking-wider">Detected Risk Alerts</h4>
                
                {overdueTasks.map((t) => (
                  <div key={t._id} className="flex items-center justify-between rounded-xl border border-slate-200 dark:border-[#1e2942] bg-slate-50 dark:bg-[#080c17] p-3 text-xs">
                    <div className="flex items-center gap-3">
                      <span className="h-2 w-2 rounded-full bg-red-500 shrink-0" />
                      <div>
                        <p className="font-semibold text-slate-800 dark:text-slate-200">{t.title}</p>
                        <span className="text-[10px] text-slate-400">Due: {new Date(t.dueDate).toLocaleDateString()}</span>
                      </div>
                    </div>
                    <span className="rounded bg-red-500/10 px-2 py-0.5 text-[10px] font-bold text-red-500 uppercase">Overdue</span>
                  </div>
                ))}

                {overdueTasks.length === 0 && unassignedUrgent.length === 0 && (
                  <div className="p-6 text-center text-xs text-slate-400 dark:text-slate-500">
                    🎉 Excellent! Zero high-risk bottlenecks detected in this project.
                  </div>
                )}
              </div>

              <div className="flex justify-end pt-2">
                <button
                  onClick={handleFixRisks}
                  className="flex items-center gap-2 rounded-2xl bg-brand-600 px-5 py-2.5 text-xs font-bold text-white hover:bg-brand-700 transition shadow-sm"
                >
                  <Zap className="h-4 w-4" />
                  1-Click AI Workload Balance
                </button>
              </div>
            </div>
          )}

          {/* 3. EXECUTIVE SUMMARY */}
          {activeTab === 'summary' && (
            <div className="space-y-5">
              <div className="rounded-2xl border border-slate-200 dark:border-[#1e2942] bg-slate-50 dark:bg-[#080c17] p-5 font-mono text-xs text-slate-700 dark:text-slate-300 leading-relaxed whitespace-pre-wrap">
                {executiveSummaryText}
              </div>

              <div className="flex justify-end">
                <button
                  onClick={handleCopySummary}
                  className="flex items-center gap-2 rounded-2xl border border-slate-200 dark:border-[#1e2942] bg-white dark:bg-[#12182b] px-5 py-2.5 text-xs font-bold text-slate-800 dark:text-slate-200 hover:border-brand-500 transition"
                >
                  {copiedSummary ? <Check className="h-4 w-4 text-emerald-500" /> : <Copy className="h-4 w-4" />}
                  <span>{copiedSummary ? 'Copied to Clipboard!' : 'Copy AI Report'}</span>
                </button>
              </div>
            </div>
          )}

        </div>
      </div>
    </div>
  );
};

export default AiAssistantModal;
